CREATE TABLE accounts
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    number      VARCHAR(64)  NOT NULL,
    holder_name VARCHAR(128) NOT NULL,
    active      BOOLEAN NOT NULL DEFAULT TRUE,
    currency    VARCHAR(3) NOT NULL,
    balance     DECIMAL(19, 4) NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    version     BIGINT NOT NULL DEFAULT 0,
    CHECK ( balance >= 0 ),
    CONSTRAINT pk_accounts PRIMARY KEY (id)
);

CREATE TABLE transactions
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account_id  BIGINT NOT NULL,
    type        VARCHAR(16) NOT NULL,
    amount      DECIMAL(19, 4) NOT NULL,
    currency    VARCHAR(3) NOT NULL,
    description VARCHAR(255),
    status      VARCHAR(16) NOT NULL DEFAULT 'APPROVED',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    version     BIGINT NOT NULL DEFAULT 0,
    CHECK ( amount > 0 ),
    CHECK ( type in ('DEBIT', 'CREDIT')),
    CONSTRAINT pk_transactions PRIMARY KEY (id)
);
ALTER TABLE accounts
    ADD CONSTRAINT uc_accounts_number UNIQUE (number);

CREATE INDEX idx_tx_account_created_at ON transactions (account_id, created_at DESC);

ALTER TABLE transactions
    ADD CONSTRAINT FK_TRANSACTIONS_ON_ACCOUNT FOREIGN KEY (account_id) REFERENCES accounts (id);