CREATE TABLE accounts
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    number      VARCHAR(64)  NOT NULL,
    holder_name VARCHAR(128) NOT NULL,
    active      BOOLEAN NOT NULL DEFAULT TRUE,
    currency    VARCHAR(3) NOT NULL,
    balance     DECIMAL(19, 4) NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    version     BIGINT NOT NULL DEFAULT 0,
    CHECK ( balance >= 0 ),
    CONSTRAINT pk_accounts PRIMARY KEY (id)
);

ALTER TABLE accounts
    ADD CONSTRAINT uc_accounts_number UNIQUE (number);